# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/work/empire/ProxyNet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/work/empire/ProxyNet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/empire/ProxyNet/CMakeFiles /home/work/empire/ProxyNet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/work/empire/ProxyNet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named socket

# Build rule for target.
socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socket
.PHONY : socket

# fast build rule for target.
socket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/build
.PHONY : socket/fast

#=============================================================================
# Target rules for targets named sha256

# Build rule for target.
sha256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sha256
.PHONY : sha256

# fast build rule for target.
sha256/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sha256.dir/build.make CMakeFiles/sha256.dir/build
.PHONY : sha256/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named ProxyNet

# Build rule for target.
ProxyNet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProxyNet
.PHONY : ProxyNet

# fast build rule for target.
ProxyNet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProxyNet.dir/build.make CMakeFiles/ProxyNet.dir/build
.PHONY : ProxyNet/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProxyNet.dir/build.make CMakeFiles/ProxyNet.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProxyNet.dir/build.make CMakeFiles/ProxyNet.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProxyNet.dir/build.make CMakeFiles/ProxyNet.dir/main.cpp.s
.PHONY : main.cpp.s

source/crypto/sha256.o: source/crypto/sha256.cpp.o
.PHONY : source/crypto/sha256.o

# target to build an object file
source/crypto/sha256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sha256.dir/build.make CMakeFiles/sha256.dir/source/crypto/sha256.cpp.o
.PHONY : source/crypto/sha256.cpp.o

source/crypto/sha256.i: source/crypto/sha256.cpp.i
.PHONY : source/crypto/sha256.i

# target to preprocess a source file
source/crypto/sha256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sha256.dir/build.make CMakeFiles/sha256.dir/source/crypto/sha256.cpp.i
.PHONY : source/crypto/sha256.cpp.i

source/crypto/sha256.s: source/crypto/sha256.cpp.s
.PHONY : source/crypto/sha256.s

# target to generate assembly for a file
source/crypto/sha256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sha256.dir/build.make CMakeFiles/sha256.dir/source/crypto/sha256.cpp.s
.PHONY : source/crypto/sha256.cpp.s

source/server/server.o: source/server/server.cpp.o
.PHONY : source/server/server.o

# target to build an object file
source/server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/server/server.cpp.o
.PHONY : source/server/server.cpp.o

source/server/server.i: source/server/server.cpp.i
.PHONY : source/server/server.i

# target to preprocess a source file
source/server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/server/server.cpp.i
.PHONY : source/server/server.cpp.i

source/server/server.s: source/server/server.cpp.s
.PHONY : source/server/server.s

# target to generate assembly for a file
source/server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/server/server.cpp.s
.PHONY : source/server/server.cpp.s

source/socket/server_socket.o: source/socket/server_socket.cpp.o
.PHONY : source/socket/server_socket.o

# target to build an object file
source/socket/server_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/source/socket/server_socket.cpp.o
.PHONY : source/socket/server_socket.cpp.o

source/socket/server_socket.i: source/socket/server_socket.cpp.i
.PHONY : source/socket/server_socket.i

# target to preprocess a source file
source/socket/server_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/source/socket/server_socket.cpp.i
.PHONY : source/socket/server_socket.cpp.i

source/socket/server_socket.s: source/socket/server_socket.cpp.s
.PHONY : source/socket/server_socket.s

# target to generate assembly for a file
source/socket/server_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socket.dir/build.make CMakeFiles/socket.dir/source/socket/server_socket.cpp.s
.PHONY : source/socket/server_socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ProxyNet"
	@echo "... server"
	@echo "... sha256"
	@echo "... socket"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/crypto/sha256.o"
	@echo "... source/crypto/sha256.i"
	@echo "... source/crypto/sha256.s"
	@echo "... source/server/server.o"
	@echo "... source/server/server.i"
	@echo "... source/server/server.s"
	@echo "... source/socket/server_socket.o"
	@echo "... source/socket/server_socket.i"
	@echo "... source/socket/server_socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

